pipeline {
    agent any
	
    stages {
        stage('Build') {
            steps {
                bat 'mvn clean'
                bat 'mvn compile'
            }
        }
        stage('Test') {
            steps {
                script {
                    def testExitCode = bat(script: 'mvn test -Dcucumber.options="stc/test/java/features', returnStatus: true)
                    if (testExitCode != 0) {
                        echo "⚠️ Algunos tests fallaron. Código: ${testExitCode}"
                        currentBuild.result = 'UNSTABLE'
                    }
                }
            }
        }
        stage('Reporte Cucumber') {
            steps {
                bat 'mvn verify'
            }
        }
    }
    post {
        always {
            // Publicar reportes JUnit si deseas
            junit '**/target/surefire-reports/*.xml'

            // Publicar el reporte HTML si usas HTML Publisher
            publishHTML([
                reportDir: 'target/cucumber-html-reports',
                reportFiles: 'overview-features.html',
                reportName: 'Reporte de Cucumber'
            ])
        }
    }

    /*post {
        always {
            emailext (
                subject: "Resultado del Job: ${env.JOB_NAME} #${env.BUILD_NUMBER}",
                body: """<p>Build finalizado.</p>
                         <p>Estado: ${currentBuild.result}</p>
                         <p>Revisar detalles en Jenkins: ${env.BUILD_URL}</p>""",
                mimeType: 'text/html',
                to: "hotdog112277@gmail.com"
            )
        }
    }*/
}
